name: Deploy React to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs # Define que os comandos rodem dentro de /docs
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Atualizado para evitar avisos de depreciação
          cache: 'npm'
          # Informa ao setup-node exatamente onde está o arquivo de dependências
          cache-dependency-path: './docs/package-lock.json' 
          
      - run: npm install
      - run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Garante que o artefato seja pego da pasta dist dentro de docs
          path: ./docs/dist 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4